spring:
  cloud:
    config:
      override-none: true
  application:
    name: item-service
  rabbitmq:
    host: 192.168.126.131
    port: 15672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka

server:
  port: 8001